services:
  app:
    build:
      context: .
      target: production
      args:
        - NODE_VERSION=20.11.1
        - NODE_PRODUCTION_VERSION=20
    tty: true
    volumes:
      - .:/opt/app:cached
      - node-modules-volume:/opt/app/node_modules
volumes:
  node-modules-volume: null
